[book]
authors = ["Daniel Marriner"]
language = "en"
multilingual = false
src = "src"
title = "Developer Notebook"

[output.html]
additional-css = ["custom.css"]

[output.html.fold]
enable = true
level = 1

[output.html.playpen]
editable = true
copy-js = true
line-numbers = true

[build]
build-dir = "./docs"
